-- AlterTable
ALTER TABLE "User" ADD COLUMN     "accentHue" INTEGER NOT NULL DEFAULT 260,
ADD COLUMN     "overlayBlur" INTEGER NOT NULL DEFAULT 18,
ADD COLUMN     "overlayOpacity" DOUBLE PRECISION NOT NULL DEFAULT 0.35;
